

# .semgrep/.semgrep.yml
# 메인 설정: 공식 packs + 로컬 규칙 포함
configs:
  - p/ci
  - p/security-audit
  - p/secrets
  - p/php
  - p/javascript

# 프로젝트 커스텀 규칙 파일들 (순서대로 적용)
include:
  - $GITHUB_WORKSPACE/.semgrep/rules-xss.yml
  - $GITHUB_WORKSPACE/.semgrep/rules-upload.yml
  - $GITHUB_WORKSPACE/.semgrep/rules-sensitive.yml

# 기본 제외 (추가로 wp-includes/wp-admin도 필요하면 추가)
exclude:
  - node_modules
  - vendor
  - .git
  - .github
  - dist
  - build
  - "**/*.min.js"
  - wp-includes/**
  - wp-admin/**

paths:
  include:
    - "src/**"
    - "**/*.php"
